### ISSUE TITLE
Offline download of some targets fail when HEVC is not enabled

### ISSUE THREAD

**Issue by graysky2** [enen92/screensaver.atv4#49]
Attempting to "Download Videos" for the following targets results in an error and failure to download:
* All
* California to Vegas
* Hong Kong

On the "Aerial Screensavers" tab I have:
```
Show start notification [ X ]
Show preview windows [ ]
Enable 4K (default 1080p) [ ]
Enable HDR [ ]
Enable HEVC (required for 4K/HDR) [ ]
```

Kodi.log when attempting to download from the "All" target is below.  Similar output when using the other two targets.
```
2021-04-29 06:11:40.006 T:153130   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument of type 'NoneType' is not iterable
                                                   Traceback (most recent call last):
                                                     File "/usr/share/kodi/addons/screensaver.atv4/entrypointscript.py", line 13, in <module>
                                                       atv.run(len(sys.argv) > 1)
                                                     File "/usr/share/kodi/addons/screensaver.atv4/resources/lib/atv.py", line 163, in run
                                                       offline()
                                                     File "/usr/share/kodi/addons/screensaver.atv4/resources/lib/offline.py", line 64, in offline
                                                       if "https" in url:
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   -->End of Python script error report<--
                                                   
2021-04-29 06:11:40.028 T:153130    INFO <general>: Python interpreter stopped
```

**Comment by kubedzero** [comment]
This should be able to be closed, as it is fixed by #51
